### Variables
@baseUrl = http://localhost:3001

### 1. Get all live persons
GET {{baseUrl}}/api/persons

###

### 2. Add a new person to the live server
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "Adfrreu",
    "number": "39-445323523"
}
