### Variables
@baseUrl = https://fullstack-open-five.vercel.app

### 1. Get all live persons
GET {{baseUrl}}/api/persons

###

### 2. Add a new person to the live server
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "39-44-5323523"
}
